name: Deploy site

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Préparer le site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Déployer
        uses: actions/deploy-pages@v4
